import type { Profile, ArchiveEntry, Status } from '@/lib/types';

export const profile: Profile = {
  fullName: 'Farah Ismail',
  headline: 'Architect · Fashion Photographer · Art Director · Model',
  bio: 'Multidisciplinary creative based in Kuala Lumpur, working across architecture, fashion photography, art direction, and modelling. My practice explores the intersections of built environment, visual culture, and personal identity — rooted in the textures of Southeast Asian urbanism.',
  roles: ['Architect', 'Fashion Photographer', 'Art Director', 'Model'],
  email: 'farah@konteks.kl',
  website: 'https://konteks.kl',
  instagram: '@farahismail',
  linkedin: 'farah-ismail',
  location: 'Kuala Lumpur, Malaysia',
  nationality: 'Malaysian',
  basedIn: 'KL, Malaysia',
};

export const archiveEntries: ArchiveEntry[] = [
  {
    id: 1,
    title: 'Rumah Langkawi Retreat',
    slug: 'rumah-langkawi-retreat',
    year: 2024,
    entryType: 'project',
    category: 'Residential',
    typology: 'Private Residence',
    description:
      'A single-storey tropical retreat nestled in the hills of Langkawi, designed around a central courtyard that frames views of the Andaman Sea. The structure uses reclaimed timber and local stone, with passive ventilation strategies drawn from traditional Malay kampung houses.',
    client: 'Private Client',
    location: 'Langkawi, Kedah',
    duration: '14 months',
    tags: ['tropical', 'courtyard', 'passive cooling', 'timber', 'island'],
    coordinates: [99.80, 6.35],
    status: 'ongoing',
    updates: [
      { date: '2024-11-20', text: 'Roof structure complete — reclaimed meranti beams in place. The grain patterns are stunning against the sky.', type: 'milestone' },
      { date: '2024-09-15', text: 'Visited the stone quarry in Langkawi for the courtyard paving. Found a beautiful grey limestone with fossil traces.', type: 'note' },
      { date: '2024-07-03', text: 'Foundation pour day. Monsoon held off just long enough.', type: 'photo' },
      { date: '2024-05-18', text: 'Thinking about how kampung houses never fight the climate — they negotiate with it. This project is my attempt at that conversation.', type: 'thought' },
      { date: '2024-03-01', text: 'Project kickoff. First site visit to the hillside plot — the Andaman Sea view is extraordinary from the northwest corner.', type: 'milestone' },
    ],
  },
  {
    id: 2,
    title: 'Brickfields Live-Work Lofts',
    slug: 'brickfields-live-work-lofts',
    year: 2023,
    entryType: 'project',
    category: 'Residential',
    typology: 'Mixed-Use Residential',
    description:
      'Adaptive reuse of a pre-war shophouse row in Brickfields into eight live-work loft units for young creatives. The design preserves the original five-foot way arcade while inserting mezzanine levels and a shared rooftop garden with views toward KL Sentral.',
    client: 'Harta Urban Sdn Bhd',
    location: 'Brickfields, Kuala Lumpur',
    duration: '18 months',
    tags: ['adaptive reuse', 'shophouse', 'live-work', 'urban infill'],
    coordinates: [101.6861, 3.1325],
    status: 'complete',
    updates: [
      { date: '2023-12-10', text: 'All eight units occupied. The rooftop garden is already becoming a gathering point — exactly as hoped.', type: 'milestone' },
      { date: '2023-08-22', text: 'Five-foot way arcade restoration complete. The original tiles were hiding under three layers of cement.', type: 'photo' },
      { date: '2023-05-14', text: 'The mezzanine insertions are working beautifully with the original timber trusses. Light filters through the gaps.', type: 'note' },
      { date: '2023-02-01', text: 'There is something sacred about peeling back layers of a building to find its original self underneath.', type: 'thought' },
    ],
  },
  {
    id: 3,
    title: 'Medan Selera Taman Tun',
    slug: 'medan-selera-taman-tun',
    year: 2022,
    entryType: 'project',
    category: 'Commercial',
    typology: 'Food Court & Market',
    description:
      'Design of an open-air hawker centre in TTDI that reinterprets the traditional medan selera as a social condenser. Tensile fabric canopies shade 32 stalls arranged around a sunken communal dining area, with integrated rainwater harvesting and misting systems.',
    client: 'DBKL',
    location: 'Taman Tun Dr Ismail, Kuala Lumpur',
    duration: '10 months',
    tags: ['hawker centre', 'public space', 'tensile structure', 'community'],
    coordinates: [101.6318, 3.1358],
    status: 'complete',
    updates: [
      { date: '2022-11-30', text: 'Grand opening! Packed house — the misting system kept everyone cool even at noon. The aunties approved.', type: 'milestone' },
      { date: '2022-09-05', text: 'Tensile canopy installation complete. The fabric catches the afternoon light in ways I did not anticipate.', type: 'photo' },
      { date: '2022-06-20', text: 'Rainwater harvesting tanks integrated beneath the sunken dining area. Dual purpose: structure and sustainability.', type: 'note' },
      { date: '2022-03-12', text: 'The best public spaces are not designed — they are negotiated with the community. Spent the morning with the hawkers discussing stall layouts.', type: 'thought' },
    ],
  },
  {
    id: 4,
    title: 'George Town Creative Hub',
    slug: 'george-town-creative-hub',
    year: 2021,
    entryType: 'project',
    category: 'Commercial',
    typology: 'Co-working & Gallery',
    description:
      'Transformation of a derelict godown on Weld Quay into a three-storey creative hub housing co-working spaces, a ground-floor gallery, and a ceramics workshop. The heritage facade is retained, with a new steel-and-glass insertion that reads as a building within a building.',
    client: 'George Town Heritage Inc.',
    location: 'George Town, Penang',
    duration: '22 months',
    tags: ['heritage', 'adaptive reuse', 'godown', 'gallery', 'coworking'],
    coordinates: [100.3388, 5.4141],
    status: 'complete',
    updates: [
      { date: '2021-10-15', text: 'Opening night. The steel-and-glass insertion glows at night — the building within a building reads exactly as intended.', type: 'milestone' },
      { date: '2021-07-20', text: 'Heritage facade scaffolding down. Every crack and patina preserved. The godown is breathing again.', type: 'photo' },
      { date: '2021-04-08', text: 'Ground floor gallery first test hang. The raw concrete walls are the perfect backdrop.', type: 'note' },
      { date: '2021-01-22', text: 'Walking through Weld Quay at dawn, imagining these godowns full of life again. Heritage is not about freezing time — it is about letting it flow through.', type: 'thought' },
    ],
  },
  {
    id: 5,
    title: 'Sungai Pinang Riverfront Masterplan',
    slug: 'sungai-pinang-riverfront-masterplan',
    year: 2020,
    entryType: 'project',
    category: 'Urban Planning',
    typology: 'Riverfront Masterplan',
    description:
      'A 2.4 km riverfront regeneration masterplan for Sungai Pinang in Penang, developed during my time at Think City. The proposal reconnects the city to its waterway through a sequence of public parks, floating markets, pedestrian bridges, and remediated wetlands.',
    client: 'Think City / Penang State Government',
    organization: 'Think City',
    role: 'Project Architect',
    location: 'Penang',
    duration: '24 months',
    tags: ['masterplan', 'riverfront', 'public realm', 'remediation', 'wetland'],
    coordinates: [100.3195, 5.4036],
    status: 'complete',
    updates: [
      { date: '2020-12-01', text: 'Masterplan submitted to Penang State Government. Two years of work distilled into one vision.', type: 'milestone' },
      { date: '2020-08-15', text: 'Community feedback sessions complete. The floating market concept resonated deeply with the older residents who remember the original river trade.', type: 'note' },
      { date: '2020-05-20', text: 'Wetland remediation pilot section showing promising water quality results after just three months.', type: 'photo' },
      { date: '2020-02-10', text: 'Rivers are the original public spaces. Before roads, before plazas — there was the riverbank.', type: 'thought' },
    ],
  },
  {
    id: 6,
    title: 'Kampung Bharu Urban Framework',
    slug: 'kampung-bharu-urban-framework',
    year: 2019,
    entryType: 'project',
    category: 'Urban Planning',
    typology: 'Urban Design Framework',
    description:
      'A sensitive urban design framework for Kampung Bharu that proposes incremental densification while preserving the Malay reserve character of the neighbourhood. The strategy centres on community land trusts, heritage lot guidelines, and a network of pedestrian mews.',
    client: 'Think City / Perbadanan Kampung Bharu',
    organization: 'Think City',
    role: 'Urban Designer',
    location: 'Kampung Bharu, Kuala Lumpur',
    duration: '16 months',
    tags: ['urban framework', 'heritage', 'community', 'densification', 'Malay reserve'],
    coordinates: [101.7028, 3.1648],
    status: 'complete',
    updates: [
      { date: '2019-11-28', text: 'Framework adopted by Perbadanan Kampung Bharu. The community land trust model is a first for KL.', type: 'milestone' },
      { date: '2019-08-14', text: 'Mapped every heritage lot in the kampung. Some timber houses date back to the 1920s — extraordinary survivors.', type: 'note' },
      { date: '2019-05-03', text: 'The pedestrian mews concept draws from the kampung lorong — narrow paths where neighbours meet. Density does not have to erase intimacy.', type: 'thought' },
      { date: '2019-02-18', text: 'First community engagement workshop. The residents know their neighbourhood better than any survey could tell us.', type: 'milestone' },
    ],
  },
  {
    id: 7,
    title: 'Bayangan — Fashion Editorial',
    slug: 'bayangan-fashion-editorial',
    year: 2024,
    entryType: 'project',
    category: 'Fashion Photography',
    typology: 'Editorial',
    description:
      'A 12-image editorial series shot in the brutalist car parks of Pekeliling Flats before their demolition, exploring the interplay of shadow, concrete geometry, and flowing batik-printed silks. Published in Tatler Asia.',
    client: 'Tatler Asia',
    location: 'Pekeliling, Kuala Lumpur',
    duration: '3 weeks',
    tags: ['editorial', 'brutalism', 'batik', 'shadow', 'demolition'],
    coordinates: [101.6970, 3.1735],
    status: 'complete',
    updates: [
      { date: '2024-06-01', text: 'Published in Tatler Asia. The demolition has started — these images are now the last record of those spaces.', type: 'milestone' },
      { date: '2024-04-18', text: 'Final selects done. The shadow play between the concrete fins and the batik silks exceeded every expectation.', type: 'photo' },
      { date: '2024-03-25', text: 'Shoot day at Pekeliling. The concrete geometry created natural light boxes — no artificial lighting needed.', type: 'note' },
      { date: '2024-03-10', text: 'Brutalism and batik share a DNA of repetition and rhythm. One is machine-made, the other hand-drawn — but the logic is the same.', type: 'thought' },
    ],
  },
  {
    id: 8,
    title: 'Cahaya Hujan — Monsoon Collection',
    slug: 'cahaya-hujan-monsoon-collection',
    year: 2023,
    entryType: 'project',
    category: 'Fashion Photography',
    typology: 'Campaign',
    description:
      'Campaign photography for Alia Bastamam\'s monsoon-inspired ready-to-wear collection. Shot on location at Sekinchan paddy fields during the northeast monsoon, using only natural light and rain to create a series of images that collapse the boundary between garment and landscape.',
    client: 'Alia Bastamam',
    location: 'Sekinchan, Selangor',
    duration: '2 weeks',
    tags: ['campaign', 'monsoon', 'paddy fields', 'natural light', 'RTW'],
    coordinates: [101.1008, 3.5021],
    status: 'complete',
    updates: [
      { date: '2023-12-20', text: 'Campaign launched. Alia says the paddy field images are her favourite work to date.', type: 'milestone' },
      { date: '2023-11-28', text: 'Rain started mid-shoot. Instead of sheltering, we kept shooting — the rain on the silk created something we could never have planned.', type: 'photo' },
      { date: '2023-11-15', text: 'Scouted Sekinchan during golden hour. The paddy fields at dusk are liquid gold.', type: 'note' },
      { date: '2023-11-01', text: 'Fashion photography should not fight nature. The best images happen when the garment and the landscape become inseparable.', type: 'thought' },
    ],
  },
  {
    id: 9,
    title: 'Struktur — Architecture Meets Fashion',
    slug: 'struktur-architecture-meets-fashion',
    year: 2022,
    entryType: 'project',
    category: 'Art Direction',
    typology: 'Exhibition',
    description:
      'Art direction for a crossover exhibition at ILHAM Gallery that paired architectural models with fashion garments, exploring shared vocabularies of structure, drape, and enclosure. Collaborated with three Malaysian fashion designers and two architecture studios.',
    client: 'ILHAM Gallery',
    collaborators: ['Khoon Hooi', 'Fiziwoo', 'Studio Bikin', 'WHBC Architects'],
    location: 'ILHAM Gallery, Kuala Lumpur',
    duration: '4 months',
    tags: ['exhibition', 'crossover', 'architecture', 'fashion', 'curation'],
    coordinates: [101.7130, 3.1525],
    status: 'complete',
    updates: [
      { date: '2022-10-05', text: 'Exhibition opening night at ILHAM. The pairing of Khoon Hooi gowns with WHBC structural models was electric.', type: 'milestone' },
      { date: '2022-08-20', text: 'Gallery layout finalised. Each pair occupies a plinth — model and garment facing each other like a conversation.', type: 'note' },
      { date: '2022-06-12', text: 'Architecture and fashion both give form to the void. One shelters the body, the other adorns it — but the thinking is the same.', type: 'thought' },
      { date: '2022-04-01', text: 'First studio visit to Fiziwoo. His draping technique mirrors the way I think about tensile structures.', type: 'note' },
    ],
  },
  {
    id: 10,
    title: 'Nusantara Vogue Feature',
    slug: 'nusantara-vogue-feature',
    year: 2025,
    entryType: 'project',
    category: 'Modelling',
    typology: 'Editorial Feature',
    description:
      'Featured as model and co-creative-director for a Vogue Singapore spread celebrating Southeast Asian creatives who work across disciplines. Shot at the National Textile Museum in KL, wearing pieces by local designers styled against heritage loom displays.',
    client: 'Vogue Singapore',
    location: 'National Textile Museum, Kuala Lumpur',
    duration: '1 week',
    tags: ['vogue', 'modelling', 'Nusantara', 'textile', 'heritage'],
    coordinates: [101.6940, 3.1483],
    status: 'complete',
    updates: [
      { date: '2025-02-15', text: 'Issue out. Seeing myself on the page next to the heritage looms felt like a homecoming.', type: 'milestone' },
      { date: '2025-01-20', text: 'Shoot wrapped at the National Textile Museum. The weavers stayed to watch — their reaction meant everything.', type: 'photo' },
      { date: '2025-01-10', text: 'To model is to lend your body to someone else\'s vision. To co-direct is to shape that vision. Both require surrender.', type: 'thought' },
      { date: '2024-12-05', text: 'Pre-production meeting with Vogue Singapore. Pitched the idea of shooting against active loom displays — approved.', type: 'note' },
    ],
  },
  {
    id: 11,
    title: 'Garis & Ruang — Solo Exhibition',
    slug: 'garis-dan-ruang-solo-exhibition',
    year: 2023,
    entryType: 'project',
    category: 'Artworks',
    typology: 'Solo Exhibition',
    description:
      'A solo exhibition of large-format ink and graphite drawings that translate architectural plan drawings into abstract compositions. The works explore the tension between precision and gesture, featuring plans of demolished KL buildings redrawn from memory at 1:1 scale on unstretched canvas.',
    client: 'Wei-Ling Gallery',
    location: 'Wei-Ling Gallery, Kuala Lumpur',
    duration: '6 weeks exhibition / 8 months production',
    tags: ['drawing', 'ink', 'graphite', 'architecture', 'memory', 'abstraction'],
    coordinates: [101.6735, 3.1133],
    status: 'complete',
    updates: [
      { date: '2023-09-08', text: 'Exhibition closed after six weeks. Every piece sold. The demolished buildings live on in other people\'s homes now.', type: 'milestone' },
      { date: '2023-07-28', text: 'Opening night at Wei-Ling. Standing in front of the 1:1 drawings felt like standing inside the buildings again.', type: 'milestone' },
      { date: '2023-04-15', text: 'Eight months of drawing. My hands remember floor plans my eyes have forgotten. Memory is stored in the body.', type: 'thought' },
      { date: '2023-01-10', text: 'Started the series. First piece: the floor plan of Bok House, drawn from memory on unstretched canvas.', type: 'note' },
    ],
  },
  {
    id: 12,
    title: 'Lapisan — Mixed Media Series',
    slug: 'lapisan-mixed-media-series',
    year: 2025,
    entryType: 'project',
    category: 'Artworks',
    typology: 'Ongoing Series',
    description:
      'An ongoing body of mixed-media work combining cyanotype prints of architectural blueprints with hand-embroidered songket motifs. Each piece layers the technical with the handmade, the colonial with the indigenous, questioning what is considered structure and what is considered ornament.',
    location: 'Studio, Kuala Lumpur',
    duration: 'Ongoing',
    tags: ['cyanotype', 'embroidery', 'songket', 'mixed media', 'blueprint'],
    coordinates: [101.6869, 3.1390],
    status: 'ongoing',
    updates: [
      { date: '2025-03-01', text: 'Piece 07 complete. The songket thread on cyanotype is becoming more confident — letting the motifs break free from the grid.', type: 'milestone' },
      { date: '2025-01-18', text: 'Learning traditional songket patterns from a master weaver in Terengganu. The mathematics embedded in the motifs is extraordinary.', type: 'note' },
      { date: '2024-10-05', text: 'The colonial blueprint is a tool of control. The songket is a tool of identity. Layering one over the other asks: who gets to define structure?', type: 'thought' },
      { date: '2024-08-12', text: 'First successful cyanotype exposure on handwoven cotton. The blueprint lines glow beneath the embroidery.', type: 'photo' },
      { date: '2024-06-01', text: 'Series concept crystallised. Blueprint + songket. Technical + handmade. Colonial + indigenous.', type: 'milestone' },
    ],
  },
  {
    id: 13,
    title: 'Bachelor of Architecture (Hons)',
    slug: 'bachelor-of-architecture',
    year: 2015,
    endYear: 2018,
    entryType: 'education',
    category: 'Residential',
    typology: 'Undergraduate Degree',
    organization: 'Universiti Teknologi Malaysia',
    role: 'Student',
    description:
      'Five-year professional architecture programme at UTM Skudai. Final-year thesis explored adaptive reuse strategies for abandoned estate worker housing in Johor, proposing a co-operative housing model that preserves collective memory while enabling contemporary living.',
    location: 'Skudai, Johor',
    duration: '2015–2018',
    tags: ['education', 'architecture', 'UTM', 'thesis', 'adaptive reuse'],
    coordinates: [103.6656, 1.5425],
    status: 'complete',
    updates: [
      { date: '2018-06-20', text: 'Graduated with Honours. Thesis on adaptive reuse of estate worker housing received the Dean\'s Award.', type: 'milestone' },
      { date: '2017-11-15', text: 'Thesis defence complete. The examiners pushed hard on the co-operative housing model — but it held up.', type: 'note' },
      { date: '2016-08-01', text: 'Semester in Johor documenting abandoned estate housing. These places hold stories that blueprints cannot capture.', type: 'thought' },
    ],
  },
  {
    id: 14,
    title: 'Urban Regeneration Designer — Think City',
    slug: 'think-city-urban-designer',
    year: 2018,
    endYear: 2021,
    entryType: 'job',
    category: 'Urban Planning',
    typology: 'Full-time Position',
    organization: 'Think City',
    role: 'Urban Regeneration Designer',
    description:
      'Three years at Think City working on urban regeneration projects across Penang and KL. Led the design team on the Sungai Pinang riverfront masterplan and contributed to the Kampung Bharu urban framework. Developed skills in community engagement, heritage assessment, and policy-informed design.',
    location: 'George Town, Penang / Kuala Lumpur',
    duration: '2018–2021',
    tags: ['urban design', 'Think City', 'regeneration', 'heritage', 'policy'],
    coordinates: [100.3388, 5.4141],
    status: 'complete',
    updates: [
      { date: '2021-03-31', text: 'Last day at Think City. Three years of incredible mentorship. Time to build my own practice.', type: 'milestone' },
      { date: '2020-06-10', text: 'Led the Sungai Pinang masterplan presentation to the state government. Nerve-wracking but exhilarating.', type: 'note' },
      { date: '2019-09-01', text: 'Think City taught me that good design is 30% drawing and 70% listening.', type: 'thought' },
      { date: '2018-07-15', text: 'First day at Think City, George Town. The office is in a restored shophouse — already learning by osmosis.', type: 'milestone' },
    ],
  },
  {
    id: 15,
    title: 'Dewan Filharmonik Petronas Pop-Up Pavilion',
    slug: 'dfp-popup-pavilion',
    year: 2021,
    entryType: 'project',
    category: 'Commercial',
    typology: 'Temporary Pavilion',
    description:
      'A temporary timber-lattice pavilion in the KLCC park esplanade designed for the Dewan Filharmonik Petronas outdoor concert season. The parametrically generated shell form acts as both acoustic reflector and rain shelter, assembled from 1,200 CNC-cut plywood ribs.',
    client: 'Dewan Filharmonik Petronas',
    location: 'KLCC Park, Kuala Lumpur',
    duration: '5 months design + 3 weeks assembly',
    tags: ['pavilion', 'parametric', 'timber', 'acoustic', 'temporary'],
    coordinates: [101.7134, 3.1578],
    status: 'complete',
    updates: [
      { date: '2021-09-18', text: 'First concert under the pavilion. The acoustic performance exceeded the simulation — the shell shape works.', type: 'milestone' },
      { date: '2021-09-01', text: 'Assembly complete in 19 days. 1,200 CNC-cut plywood ribs, zero waste, all connections dry-jointed.', type: 'photo' },
      { date: '2021-06-15', text: 'CNC cutting started. Watching the parametric design become physical — each rib slightly different from the last.', type: 'note' },
      { date: '2021-04-02', text: 'Temporary architecture is honest. It admits from the start that nothing lasts — and that gives it freedom.', type: 'thought' },
    ],
  },
  {
    id: 16,
    title: 'KL Fashion Week — Art Direction',
    slug: 'klfw-art-direction',
    year: 2024,
    entryType: 'project',
    category: 'Art Direction',
    typology: 'Event Art Direction',
    description:
      'Overall art direction for the main stage presentation at KL Fashion Week 2024. Designed the spatial concept, lighting scheme, and visual identity — transforming the Pavilion KL event hall into a gridded landscape of illuminated acrylic columns referencing the Petronas Towers\' floor plate geometry.',
    client: 'KL Fashion Week',
    collaborators: ['Pavilion KL', 'Lightcraft Studio'],
    location: 'Pavilion KL, Kuala Lumpur',
    duration: '3 months',
    tags: ['fashion week', 'stage design', 'lighting', 'spatial', 'identity'],
    coordinates: [101.7131, 3.1489],
    status: 'complete',
    updates: [
      { date: '2024-08-25', text: 'KLFW opening night. The acrylic columns caught every spotlight — the room became a forest of light.', type: 'milestone' },
      { date: '2024-08-10', text: 'Technical rehearsal. The lighting scheme transforms the grid from cold to warm as each collection walks.', type: 'note' },
      { date: '2024-07-15', text: 'Pavilion KL event hall is a blank canvas. The Petronas floor plate geometry gave me the grid — the light does the rest.', type: 'photo' },
      { date: '2024-06-01', text: 'Fashion shows are architecture with a four-minute lifespan. Every second must be spatially intentional.', type: 'thought' },
    ],
  },
  {
    id: 17,
    title: 'Pameran Tanah Air — Group Exhibition',
    slug: 'pameran-tanah-air',
    year: 2020,
    entryType: 'project',
    category: 'Modelling',
    typology: 'Campaign / Group Show',
    description:
      'Modelled for and co-curated a group photography exhibition at Zhongshan Building celebrating Malaysian identity through portraiture. Twelve photographers each captured a different facet of "tanah air" (homeland), with the resulting prints displayed salon-style in the building\'s former printing press.',
    client: 'Zhongshan Building Collective',
    location: 'Zhongshan Building, Kuala Lumpur',
    duration: '2 months',
    tags: ['portraiture', 'exhibition', 'identity', 'collective', 'Zhongshan'],
    coordinates: [101.6967, 3.1417],
    status: 'complete',
    updates: [
      { date: '2020-11-01', text: 'Exhibition opening at Zhongshan. Twelve photographers, twelve visions of home. The old printing press room was perfect.', type: 'milestone' },
      { date: '2020-09-20', text: 'Salon-style hanging complete. The portraits talk to each other across the wall — a visual conversation about belonging.', type: 'photo' },
      { date: '2020-07-15', text: 'Being both model and curator means seeing yourself from the outside while shaping the inside. It is disorienting and clarifying at once.', type: 'thought' },
      { date: '2020-05-01', text: 'First collective meeting at Zhongshan Building. The concept of "tanah air" sparked immediate and emotional responses from every photographer.', type: 'note' },
    ],
  },
];

export const status: Status = {
  isOnline: true,
  currentActivity: 'Working on residential concept sketches',
  lastSeen: '2025-03-11T10:30:00Z',
};
